name: Deploy to EC2

on:
  push:
    branches:
      - main  # ou a branch que você estiver usando

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare SSH Key
        run: |
          echo "$EC2_PRIVATE_KEY" > /tmp/ec2_key.ppk
          chmod 600 /tmp/ec2_key.ppk

      - name: Build Docker image
        run: |
          # Use o Dockerfile na raiz do diretório /var/www/15.228.254.240
          docker build -t my-deploy-image -f /var/www/15.228.254.240/Dockerfile /var/www/15.228.254.240

      - name: Run Docker container for deployment
        run: |
          docker run --rm -e SSH_KEY=/tmp/ec2_key.ppk my-deploy-image bash -c "
          rsync -avz -e 'plink -i \$SSH_KEY' ./ ubuntu@seu_servidor_ec2.amazonaws.com:/var/www/seu_projeto
          ssh -i \$SSH_KEY ubuntu@seu_servidor_ec2.amazonaws.com 'sudo systemctl restart nginx'
          "
