name: Deploy to EC2

on:
  push:
    branches:
      - main  # Modifique para o branch desejado

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to EC2
        run: |
          # Defina variáveis
          EC2_USER=ubuntu
          EC2_HOST=54.207.0.19
          SSH_KEY=$HOME/.ssh/ec2_key.pem
          EC2_PATH=/var/www/15.228.254.240/
          
          # Adicionar chave SSH ao agente
          mkdir -p ~/.ssh
          echo "$EC2_PRIVATE_KEY" > $SSH_KEY
          chmod 600 $SSH_KEY

          # Sincronizar arquivos com EC2
          rsync -avz -e "ssh -i $SSH_KEY -o StrictHostKeyChecking=no" ./ $EC2_USER@$EC2_HOST:$EC2_PATH

      - name: Restart Nginx
        run: |
          ssh -i $SSH_KEY -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "sudo systemctl restart nginx"

