name: Deploy to EC2

on:
  push:
    branches:
      - main  # ou a branch que você estiver usando

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare SSH Key
        run: |
          echo "$EC2_PRIVATE_KEY" > /tmp/ec2_key.ppk
          chmod 600 /tmp/ec2_key.ppk

      - name: Sync files to EC2
        run: |
          # Sincronizar arquivos do repositório com o servidor EC2
          rsync -avz -e "ssh -i /tmp/ec2_key.ppk" ./ ubuntu@54.207.0.19:/var/www/15.228.254.240

      - name: Build and run Docker container on EC2
        run: |
          ssh -i /tmp/ec2_key.ppk ubuntu@54.207.0.19 << 'EOF'
          cd /var/www/15.228.254.240
          docker build -t my-deploy-image .
          docker run --rm my-deploy-image bash -c "rsync -avz ./ ubuntu@localhost:/var/www/15.228.254.240 && sudo systemctl restart nginx"
          EOF
